apiVersion: v1
kind: Service
metadata:
  name: spa-angular-loadbalancer
  labels:
    app: spa-angular
spec:
  type: LoadBalancer
  ports:
    - name: spa-angular-loadbalancer-port
      port: 80
      protocol: TCP
  selector:
    app: spa-angular
